name: 'Setup Zernikalos Build Environment'
description: 'Setup JDK, Android SDK and Gradle for Zernikalos builds'
inputs:
  cache-read-only:
    description: 'Gradle cache read-only mode'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        build-tools: 36.0.0

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ inputs.cache-read-only }}

